function I = reciprocate(V,head,Imax)
%I=RECIPROCATE(V,HEAD,IMAX) 
% determine the TES montage that targets the sources expressed in
%   scalp potentials V, generated as a linear combination of the columns of R,
%   and constrained to a maximum delivered current of Imax
% 
%   V: nElectrodes-by-1 vector of EEG
%   head: struct with the following fields:
        % lead field matrix "R" (nElectrodes x (nVerticesx3))
        % coordinates of vertices "locs" (nVertices-by-3)
        % surface normals "surfNormals" (nVertices-by-3)
        % mesh vertices "Vertices"
        % mesh faces "Faces", 
        % the path to an EEGLAB topoplot compatible electrode location file "locFilename"
        % (optional) a cortical surface that can be generated by the software BrainStorm "cortex"
%   Imax: total current delivered in A (defaults to 0.002) 

if nargin<3, Imax=0.002; end

RR=head.R*(head.R)';

rankRR=rank(RR);
if rankRR<size(head.R,1),
    warning('R is rank-deficient.  Results will likely be wrong');
    warning('Trying to compute a regularized inverse...');
    I = regInv( RR,100 ) * V;
else
    I=RR\V;  % R is well-conditioned
end


Itotal=sum(abs([I; sum(I)]));
I=I/(Itotal/(2*Imax));


end

